### ISSUE TITLE
Image meta tag doesn't work 

### ISSUE THREAD

**Issue by duttakapil** [coderplex-org/mobile-dev-month#2]
I'm not sure why, but the image meta tag doesn't work when I try to load the [site](https://fcc-hyd.github.io/mobile-dev-month/) on social media. I'm unable to figure this out, can someone help? @vinaypuppal can you look into this?

**Comment by vinaypuppal** [comment]
@duttakapil i can see **image** in facebook open graph debugger, you can check here https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Ffcc-hyd.github.io%2Fmobile-dev-month%2F

**Comment by vinaypuppal** [comment]
@duttakapil if you expand the warnings in above link you may find
 `Invalid URLProvided og:image URL, ./img/phone.png was not a valid URL.` and further down you can see
`Canonical URL http://mobile-dev-month.surge.sh/ `.

So i fixed `og:url` in #4 , lets see if this fixes the image issue also.
